### ISSUE TITLE
No source distributions on PyPi

### ISSUE THREAD

**Issue by calvinbeeguard** [insight-platform/Similari#109]
No source distributions are available pn PyPi making it impossible to upgrade similari-trackers-rs further than version 0.26.5 using pip install --upgrade and so even with the --no-binary or --no-cache-dir options.

**Comment by bwsw** [comment]
Yes, you are right, no more source distribution. Unfortunately, I'm not planning to change CI/CD to publish the source distribution because it has no practical purpose.

**Comment by enavarro222** [comment]
We got that issue on apple M1, either source distribution or compiled code for apple silicon would be great !

**Comment by bwsw** [comment]
@enavarro222, you can build locally with instructions:
https://github.com/insight-platform/Similari?tab=readme-ov-file#build-python-api-in-host-system

The source distribution does not help with the problem because it is a Rust code, and you cannot build it automatically without a toolchain installed. Unfortunately, I do not have a Mac available to run automated or local builds, but nothing prevents from building locally.

**Comment by bwsw** [comment]
@enavarro222 
I wonder if it can do it for PyO3/Rust-based source code.

As I see, GitHub added a runner for MacOS M1, so I may try to automate the builds.

**Comment by bwsw** [comment]
Looks like the build goes normally. I will release the next minor version with builds for MacOS and sdist.

https://github.com/insight-platform/Similari/actions/runs/8001965355/job/21854218309

**Comment by bwsw** [comment]
@enavarro222 @calvinbeeguard When the build completes, you will have access to MacOS prebuilt wheels and sadist.

https://github.com/insight-platform/Similari/actions/runs/8002068475

**Comment by enavarro222** [comment]
Great !  🎉 

Thanks a lot !
